name: iOS Banking App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    name: Build, Unit Test, and UI Test
    runs-on: macos-latest
    timeout-minutes: 20

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest

    - name: Install dependencies (if needed)
      run: |
        xcodebuild -resolvePackageDependencies -project Banking-card.xcodeproj

    - name: Build app
      run: |
        xcodebuild \
          -scheme Banking-card \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO \
          ONLY_ACTIVE_ARCH=YES \
          clean build

    - name: Run Unit Tests
      run: |
        xcodebuild test \
          -scheme Banking-card \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' \
          -testPlan UnitTests \
          -enableCodeCoverage YES \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO \
          ONLY_ACTIVE_ARCH=YES
          
    - name: Run UI Tests
    
      continue-on-error: true
     
      if: ${{ github.event.inputs.run_ui_tests == 'true' }}
      run: |
        xcodebuild test \
          -scheme Banking-card \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' \
          -testPlan UITests \
          -enableCodeCoverage YES \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO \
          ONLY_ACTIVE_ARCH=YES
